### ISSUE TITLE
Unexpected error while executing...

### ISSUE THREAD

**Issue by saffull** [ayuso2013/face-recognition#12]
Unexpected error while executing: am start -n "org.opencv.javacv.facerecognition/org.opencv.javacv.facerecognition.FdActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Error while Launching activity

**Comment by dhagz** [comment]
no additional error messages provided?

**Comment by saffull** [comment]
$ adb shell am start -n "org.opencv.javacv.facerecognition/org.opencv.javacv.facerecognition.FdActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Unexpected error while executing: am start -n "org.opencv.javacv.facerecognition/org.opencv.javacv.facerecognition.FdActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Error while Launching activity

**Comment by saffull** [comment]
this isn the full message...!!

**Comment by dhagz** [comment]
Sorry, I haven't encountered that error while working on the project.

**Comment by saffull** [comment]
well then can u tell me how to use the app without opencv manager download in mobile

**Comment by ayuso2013** [comment]
Hi, the app depends on Opencv, so you have to download the opencv manager,
There are ways to link statically OpnecV, but I've never done that, Refer
to the OpenCV docs.


2016-06-04 8:57 GMT+02:00 saffull <notifications@github.com>:

**Comment by Kabir121** [comment]
HI ayuso, Saffull

I tried many examples to import project and make run Open CV examples of face recognition but could not able to implement it successfully. 

@ayuso2013 I could not able to import this example in android studio. It says library missing. This is working code ??. Apart from this sample I can able to initially set up all the configuration for Open CV. Can you help me out after downloading where I should put the library and provides path to above sample. 

In many projects I got error in jni like recently I got : OpenCV/core/core.php  file not found.

Please help me out

**Comment by saffull** [comment]
i have already seen the documentation. does they have any documentation for
android studio.

**Comment by saffull** [comment]
@Kabir121
well kabir.. i didnt have any problem opening the app directly in android studio 2.0+.
after downloading the project extract it.
from Android Studio open it by selecting out its path.. the gradle will take care of all.
all i did was to edit sdk versions in build.gradle to be compatible with mine.. other all were take care in gradle in android studio
try opening the project not importing it...i hope you got the difference

**Comment by saffull** [comment]
@Kabir121 
indirectly if you want to intialize opencv 
then do edit the **build.gradle :module app**

apply plugin: 'com.android.application'
android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"
    defaultConfig {
        applicationId "com.Vishal.opencv"
        minSdkVersion 19
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.1.1'
    **compile 'org.opencv:opencv-android:2.4.8'**
}

**repositories {
    maven {
        url 'https://raw.github.com/vRallev/mvn-repo/master/'
    }
}**

**Comment by Kabir121** [comment]
@saffull It's a project of Eclipse. I just tried to open this on Android studio but as I tried to open it it does not create gradle. And hence could not able to make changes as you told.  :|

**Comment by Kabir121** [comment]
Can you provide me working demo. It will be most helpfull to me. My email is : avi.it.128@gmail.com
I am trying for months to make this done but could not get help from anyone.

**Comment by Kabir121** [comment]
I can also come on team viewer if you can help me out in this.

**Comment by saffull** [comment]
@Kabir121 
can u tell me how you imported it on eclipse. and is it working properly...?

**Comment by Kabir121** [comment]
yes one of the example worked properly. I imported it and provide reference to open cv library. I downloaded library seperately.

**Comment by Kabir121** [comment]
@saffull  
Now I am trying to import it on Android studio 2.1. I could not able to build gradle for that and for other example studio shows me problem like OpenCV/core/core.php file not found.

**Comment by Kabir121** [comment]
@saffull  Let me tell you exactly I want to recognize lips on screen. can we implement it ?
I want to try this but  I could not able to run 1 project from months :| .

**Comment by Kabir121** [comment]
Here is the link of project I am trying to make changes and make this run: https://www.dropbox.com/s/zul6qtdgspgxwc8/OpenCV-AndroidSamples-master.zip?dl=0

**Comment by saffull** [comment]
@ayuso2013 
sometimes faces dont get saved. what do you think

**Comment by saffull** [comment]
@Kabir121 
i think you should look at opencv detection algorithm..
maybe it can help with lip detection

**Comment by Kabir121** [comment]
@saffull  yea but initially I want to atleast run one project so that I can start with that.
Have you had time to look into those projects ?

**Comment by saffull** [comment]
@Kabir121 
yes am getting some hdpi error i dont get it..
can u do one thing download the code by ayuso and open in android studio not eclipse
then resolve the errors..i think the gradle will automatically take care of it.

**Comment by Kabir121** [comment]
ok let me try it once again. @saffull

**Comment by Kabir121** [comment]
I have attached the screenshot, Kindly find. I am still facing the issue. @saffull 

![screnshot](https://cloud.githubusercontent.com/assets/1772926/15892833/b316e0ba-2d99-11e6-964b-8321404a0f9a.png)

**Comment by Kabir121** [comment]
I also tried by cloning project directly from git but could not get success. It is not creating gradle.

**Comment by saffull** [comment]
@Kabir121 
this is my project:- https://www.dropbox.com/sh/b1cehrzrcxcnudm/AACKK2mXiDWdgfL9m0Q8JDE-a?dl=0
download it and open it using android studio

**Comment by Kabir121** [comment]
@saffull I tried that project it giving error **Error:Cause: failed to find target with hash string 'Google Apis:Google Apis:21' in: sdk**

I go through below links but yet no success.  Still facing same problem:-
http://stackoverflow.com/questions/32715418/failed-to-find-target-with-hash-string-android-22
http://stackoverflow.com/questions/35450417/errorcause-failed-to-find-target-with-hash-string-google-inc-google-apis23

**Comment by Kabir121** [comment]
@saffull Thanks that working on my end now. But it does not compare save image isn't it ?

**Comment by Kabir121** [comment]
I gues you worked on Ubuntu. And I work on Windows that was the problem. @saffull

**Comment by saffull** [comment]
@Kabir121 
yes am working on ubuntu.. its much more flexible than windows.. it does compare save image.. you just need to do a simple change in code.. this you should find out..
hope everthing digs out well...
